# This workflow will lint check and test a Kotlin Android project

name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint_check:
    name: Run Lint and Ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest version of repository
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create fake secrets file
        run: cp secret.properties.example secret.properties

      - name: Run Ktlint
        run: ./gradlew -q ktlintCheck

      - name: Upload Lint Reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: lint_reports
          path: |
            app/build/reports/lint-results.html
            app/build/reports/ktlint/

  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest version of repository
      uses: actions/checkout@v2
    
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Create fake secrets file
      run: cp secret.properties.example secret.properties
    
    - name: Run Unit Tests
      run: ./gradlew -q testDebugUnitTest

    - name: Upload Unit Test Reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_reports
        path: app/build/reports/tests/testDebugUnitTest/

  integration_test:
    name: Run Integration Tests
    runs-on: macos-latest

    steps:
      - name: Checkout latest version of repository
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create fake secrets file
        run: cp secret.properties.example secret.properties

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          disable-animations: true
          script: ./gradlew -q connectedDebugAndroidTest -PwithScreenshots

      - name: Upload Integration Test Reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_reports
          path: app/build/reports/androidTests/connected/
